### ISSUE TITLE
STA9750 <GITHUB_USERNAME> MiniProject #00

### ISSUE THREAD

**Issue by annaol** [annaol/STA9750-2024-FALL#1]
Hi @michaelweylandt!

I've created my STA9750 website - check it out!

https://annaol.github.io/STA9750-2024-FALL

**Comment by michaelweylandt** [comment]
Thanks @annaol !

Peer Feedback:

- @mt1536
- @cliu98
- @greazyz

Please a look at the website associated with this GitHub repo
and provide some peer feedback to @annaol.

Website URL should be: https://annaol.github.io/STA9750-2024-FALL/

If that link doesn't work, please check out the GitHub profile for @annaol and
see if you can help them get it working.

At a minimum, please note:

1. Something you like about the submission.
2. A suggestion on how to improve it.

Feel free to link to other repos, the course documentation, or other useful
examples.

This submission is ungraded, so there's you don't need to provide
a numerical score.

Thanks!
@michaelweylandt

CC: @charles-ramirez

**Comment by cliu98** [comment]
Hey @annaol , 

I was able to access your site with no issues. I love that you put a dedication to Kiki, I hope she's enjoying as many treats and scratches in doggy heaven. 
I'd like to see an about you section as well on your portfolio too!

Best,
Chris

**Comment by mt1536** [comment]
Hi @annaol,

Great web site. I love the fact that you included a picture; that's something I will try to incorporate on my web site. To improve your web site, I would divide the text into at least 2 paragraphs to make it look better.

Regards,
mt1536

**Comment by greazyz** [comment]
Hi @annaol, thank you for sharing your story with Kiki. The photo you
included really captures the emotions in your story. You can try using
paragraphs to highlight the journey she went on with your family by adding
1 or more blank lines between the block of text.
