### ISSUE TITLE
STA/OPR 9750 annaol MiniProject #02

### ISSUE THREAD

**Issue by annaol** [annaol/STA9750-2024-FALL#3]
Hi @michaelweylandt!

I've uploaded my work for MiniProject #02 - check it out!

https://annaol.github.io/STA9750-2024-FALL/mp02.html

**Comment by michaelweylandt** [comment]
Thanks @annaol !

Peer Feedback:

- @camilomartinez777
- @Will-Peters
- @Harry-2099
- @edodia

It is now time for the peer feedback round for Mini-Project 02. Please
review @annaol's submission for this mini-project and provide peer feedback.

Using the rubric at https://michael-weylandt.com/STA9750/miniprojects/mini02.html#rubric,
please grade their submission out of a total of 50 points. Note that this
rubric is slightly different than that used for Mini-Project 01.

For each of the five categories, please give them a separate score and provide
a total (sum) score across the entire assignment. Feel free to assign extra
credit if you feel it is warranted (following the rubric).

If you give a score of less than 5 for any category, please provide a suggestion
for improvement. (You can also give suggestions for any element they did well -
more feedback is always great!)

As you go through this peer feedback exercise, think about what you particularly
like about this submission and how you can incorporate that approach in your future
work. If something is particularly insightful or creative, give some kudos!

Evaluators: This should take you around 15 minutes per peer feedback. You are
not required to engage in substantial back-and-forth with @annaol, but you are of course
welcome to initiate a discussion.

@annaol: please engage fully with your peers. They are here to help you!

Submission URL should be: https://annaol.github.io/STA9750-2024-FALL/mp02.html

Feel free to link to other repos, the course documentation, or other useful
examples.

Thanks!
@michaelweylandt

CC: @charles-ramirez

**Comment by Harry-2099** [comment]
Hey anna, 

This is a great project there's really nothing that I would change. The only comment I would add is on the plotly graphs. They were really good and added a lot to the project, however on the simpler graphs I don't know if it adds much value and thus id recommend skipping it on graphs that are very simple just to make it easier on yourself. The ploty does make a huge difference to the more complex charts however, so it was overall a very nice touch. Another point id like to add is I really enjoyed the logic of your success metric, almost like a z-score, which I thought was very smart.

Written Communication - 11/10: very detailed enjoyed your analysis 
Project Skeleton - 10/10: everything answered properly
Formatting and Display - 11/10: really nice charts and presentation overall, plotly was a plus.
Code - 10/10: logical and readable
Data Prep 10/10 

Total: 52/50

**Comment by Will-Peters** [comment]
Hey anna,

This is a great project however felt that the build up with the glimpse is too excessive, as (at least in my opinion) that is part of the back-end development work rather than needing to be shown . 

Written Communication - 8/10: Felt the analysis was too verbose, and everything was shown, rather than running assumption and key takeaways being shown, I.e. Oldest living person, glimpse etc.
Project Skeleton - 8/10: everything answered relatively properly however, without the breakout of genre (the fact it was concatenated, meant it didn't feel like it properly answered the question of which genre is becoming more popular.)
Formatting and Display - 8/10: Would recommend when demonstrating/showing the tables, there are some selects and renames to only show the relevant information/columns and named appropriately.
Code - 9/10 Key Personnel table, logic was difficult to follow
Data Prep 10/10

Total: 43/50

**Comment by Edodia** [comment]
Hi Anna, this is a great project, your analytical skills are on point.
Your graphs are beautiful and I love that they are interactive. Wehn
it coems to some of your graphs where there are numerous data points
it really makes the difference to a viewer.
written communication 10/10
project skeleton 10/10
code 11/10 for adding plotly and code folding
f & d 11/10 for adding plotly
data prep 10/10

**Comment by camilojourney** [comment]
Hi Ana,

Written Communication: 7
The report is technically sound but could benefit from brief explanations on the purpose of each task, such as why data filtering (e.g., ratings ≥ 100) is essential.  Just let me know why you are doing what you are doing to make it more sense. 

Project Structure: 8
The project structure is well-organized, covering all tasks with thorough detail. Including validation for the success metric would clarify its value and how it accurately reflects performance.

Formatting and Display: 8
The visualizations are detailed, though certain charts, like those with year-based x-axis labels, are too clustered. Line charts or adjusted label spacing would make them easier to interpret. Adding concise chart titles and captions would enhance understanding.

Code Quality: 10
The code is efficient and well-commented, achieving accurate outputs across tasks. Each function is clear, making the analysis reliable and reproducible.

Data Preparation: 10
Data preparation was meticulous, covering necessary conversions and handling missing values, ensuring high-quality results. The filtering criteria are logical and well-applied to maintain focus.

Total Score: 45

Good work, keep it up!
