### ISSUE TITLE
STA/OPR 9750 annaol MiniProject #04

### ISSUE THREAD

**Issue by annaol** [annaol/STA9750-2024-FALL#5]
Hi @michaelweylandt!

https://annaol.github.io/STA9750-2024-FALL/mp04.html

**Comment by michaelweylandt** [comment]
Thanks @annaol !

Peer Feedback:

- @chricannon
- @fatima8808
- @whaleron
- @plnrbrt

It is now time for the peer feedback round for Mini-Project 04. Please
review @annaol's submission for this mini-project and provide peer feedback.

Using the rubric at https://michael-weylandt.com/STA9750/miniprojects/mini04.html#rubric,
please grade their submission out of a total of 50 points. Note that this
rubric is slightly different than that used for Mini-Projects 01 -- 03.

For each of the five categories, please give them a separate score and provide
a total (sum) score across the entire assignment. Feel free to assign extra
credit if you feel it is warranted (following the rubric).

If you give a score of less than 5 for any category, please provide a suggestion
for improvement. (You can also give suggestions for any element they did well -
more feedback is always great!)

As you go through this peer feedback exercise, think about what you particularly
like about this submission and how you can incorporate that approach in your future
work. If something is particularly insightful or creative, give some kudos!

Evaluators: This should take you around 15 minutes per peer feedback. You are
not required to engage in substantial back-and-forth with @annaol, but you are of course
welcome to initiate a discussion.

@annaol: please engage fully with your peers. They are here to help you!

Submission URL should be: https://annaol.github.io/STA9750-2024-FALL/mp04.html

Feel free to link to other repos, the course documentation, or other useful
examples.

Thanks!
@michaelweylandt

CC: @charles-ramirez

**Comment by chricannon** [comment]
Hi @annaol, 

Excellent job on mp04! My grading is as follows - 

**Written Communication: 10/10** You described each step well and your report flows naturally. I appreciate how you walked the reader through each plan and seemed to pick up on where a reader needs more background information versus where they may not. Specifically, within Task 6, I appreciate your step by step explanation of the **ORP Plan**. Personally, reading through the 6 steps written out led me to a better understanding than should you have put all the information in one paragraph - good thinking here! 
**Project Skeleton: 11/10** You adequately completed each task and labeled each task. I especially found your task 7 to be particularly insightful - your 6 visualizations of each economic factor and its impact by the simulation-based bootstrap distribution. Extra credit for the extra work you put into task 7!
**Formatting & Display: 10/10** All tables and visualizations are well formatted. I appreciate your use of the Blockquote to include the ask of each task - definitely helps a reader understand better even before digging into your analysis. 
**Code Quality: 10/10** All code runs accordingly and is well described/commented. 
**Data Preparation:10/10** You clearly outlined all of your data acquisition. I appreciate your "Data prep" label to help guide a reader to where you cleaned and pre-processed your data. 

**Total: 51/50**

**Comment by whaleron** [comment]
Hi @annaol , you did an amazing job!
I've learned from your mp how I could do my own analysis better and improve charts. 

Writing communication: 10
Project skeleton:10
Formatting & display: 10
Code quality: 10
Data preparation: 10
Additional points: 2
Total:52/50

**Comment by fatima8808** [comment]
Hi @annaol, great job in completing your mini project 4!   You went into great detail about both pension plans and used historic data effectively to answer the tasks. Please see more details below:

**Written Communication: 9**
You communicated the motivation of this project and the purpose of your chosen datasets, as well as interpretting your visualizations and financial outcomes after running each pension plan's formulas. One suggestion I would give is if you could provide your recommendation of which plan an employee may go with at the end of your report. 

**Project Skeleton: 10**
You completed all instructor-provided tasks correctly and explained the reasoning behind your analysis and your approach to calculating benefits under each plan. I didn't find any issues here, nice work!

**Formatting & Display: 9**
Though there wasn't an animated visualization like the rubric expects us to include, you created great visualizations that are easy to read and understand, as well as your tables. I like that you added labels to each point in your plot of the TRS annual benefits as well, and it's even better that you used plotly to make your plots interactive, I'll definitely consider using this in future projects of mine!

**Code Quality: 10**
I didn't find any issues with your code, and again your explanations/motivation for your code makes it easy to follow.

**Data Preparation: 10**
You were able to import data automatically with your use of APIs while also being mindful not to show your personal API keys and reminding the user to obtain their key if they wish to reproduce this analysis.

**Total: 48/50**
Again, really nice work!

**Comment by plnrbrt** [comment]
Hi @annaol, 
Thank you for sharing your project and great job on completing the project!

Written Communication: 9/10 You explained every steps of your analysis and added comment to describe the results of your visuals. I am just taking a point off because I would have love to read your recommendations.

Project Skeleton: 9/10 Missing the Deliverable: Data-Driven Decision Recommendation.

Formatting & Display: 10/10 I really liked your visuals especially your Monte Carlo analysis, the visuals where very insightful and well presented.

Code Quality: 10/10 Nothing to report on that, everything looked good to me.

Data Preparation: 10/10 All the data was well prepared and downloaded.

Total: 48/50
